version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: app_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app_net

  app:
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app_net

volumes:
  sqlserver_data:

networks:
  app_net:
    driver: bridge
